services:
  postgres:
    image: postgres:15
    container_name: alerta-postgres
    restart: always
    environment:
      POSTGRES_DB: alertadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata_alerta:/var/lib/postgresql/data

  backend:
    build: .
    container_name: alerta-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/alertadb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  pgdata_alerta: